import { InstitutionalShell, InstitutionalHero, InstitutionalClosing, contactFor, pageMetadata } from "../institutional";
const contact = contactFor("Hola, represento una fundación y quiero conocer el acompañamiento de uHub para dar seguimiento a los proyectos que apoyamos.");
export const metadata = pageMetadata("Seguimiento para fundaciones y convocatorias", "uHub: Un acompañamiento con diagnóstico, mentores y evidencia de avance para personas y proyectos apoyados por fundaciones e instituciones.", "/fundaciones");
export default function FundacionesPage() {
  return <InstitutionalShell>
    <InstitutionalHero label="Fundaciones e instituciones que apoyan proyectos" title="Que cada apoyo tenga un camino para continuar." intro="Acompañamiento para que las personas que seleccionas en tu convocatoria conviertan su apoyo en acciones, aprendizaje y continuidad. Con criterios compartidos y evidencia útil para tu equipo." contact={contact} cta="Conversemos sobre tu programa" facts={[["Un punto de partida", "Diagnóstico por participante"], ["Seguimiento continuo", "Mentor base y apoyos especializados"], ["Evidencia de avance", "Acciones, decisiones y resultados"]]} status="Propuesta adaptable a cada convocatoria. Alcance, indicadores y duración se definen con la institución." />
    <section className="institutional-section institutional-split"><div><p className="eyebrow">Después de entregar el apoyo</p><h2>¿Qué pasa con cada proyecto?</h2></div><div><p>Un recurso o un premio abre una oportunidad. Después aparecen decisiones, obstáculos y necesidades distintas. Sin un seguimiento compartido, es difícil saber quién avanza, quién se atoró y qué apoyo necesita.</p><p>uHüb propone una forma de acompañar a las personas y reunir evidencia del proceso: qué intentaron, qué aprendieron y qué decisión tomarán después.</p></div></section>
    <section className="institutional-section"><p className="eyebrow">Un proceso que se acuerda contigo</p><h2>Del criterio común al seguimiento individual.</h2><ol className="institutional-sequence"><li><span>01 / Acordar</span><h3>Objetivos e indicadores</h3><p>Definir qué significa avanzar en tu programa, qué evidencia recoger y cómo se reportará.</p></li><li><span>02 / Acompañar</span><h3>Diagnóstico y acciones</h3><p>Establecer una línea de partida, un plan y una persona mentora que revise avances. Como referencia, una intervención de seis meses.</p></li><li><span>03 / Aprender</span><h3>Revisión y continuidad</h3><p>Detectar barreras, ajustar apoyos y cerrar con recomendaciones para cada proyecto y para futuras convocatorias.</p></li></ol></section>
    <section className="institutional-band"><p className="eyebrow">Qué recibe la institución</p><h2>Un seguimiento que ayuda a decidir.</h2><ul className="institutional-checks"><li>Diagnóstico inicial y objetivos acordados por participante.</li><li>Registro de sesiones, acciones y aprendizajes relevantes.</li><li>Reportes de avance según indicadores acordados.</li><li>Un cierre con resultados observados y recomendaciones de continuidad.</li></ul><p>Definimos contigo qué información personal puede compartirse y qué debe presentarse de manera agregada.</p></section>
    <section className="institutional-section institutional-split"><div><p className="eyebrow">La persona en el centro</p><h2>Distintos puntos de partida. Apoyos pertinentes.</h2></div><div><p>La propuesta puede adaptarse tanto a proyectos seleccionados como a personas que todavía necesitan preparar su iniciativa. Se acuerdan criterios, cupo y alcance para cada grupo.</p><p>Un mentor base ayuda a sostener el proceso. Los especialistas intervienen ante retos concretos, de acuerdo con las necesidades y los recursos del programa.</p><p className="institutional-note">Esta línea se está desarrollando a partir de la experiencia de acompañamiento de uHüb. No se presenta como un programa ya evaluado con fundaciones.</p></div></section>
    <InstitutionalClosing title="¿Qué quieres que ocurra después de tu convocatoria?" text="Comparte el perfil de participantes, los apoyos que otorgas y las decisiones que necesitas informar. Diseñamos contigo el alcance y la propuesta económica." contact={contact} cta="Conversemos sobre tu programa" pdf="/downloads/uhub-fundaciones.pdf" />
  </InstitutionalShell>;
}
