export type JourneyMode = "route" | "challenge";

// Illustrative situations, never completion requirements or promised outcomes.
export const journeyStages = [
  {
    name: "Descubrir", element: "Fuego", capacity: "Mentalidad y propósito",
    question: "¿Qué quieres poner en movimiento?",
    situation: "Tienes ganas de empezar o de volver, pero todavía necesitas elegir por dónde.",
    route: "Exploras tus motivos, tus recursos y una necesidad que te interesa atender.",
    challenge: "Revisas qué cambió en tu contexto y qué reto merece tu atención ahora.",
    action: "Hablar con una persona que vive el problema que quiero atender.",
    ownAction: "Conversar con alguien de mi entorno para contrastar el reto que elegí.",
    evidence: "Una necesidad concreta que escuchaste y una pregunta que todavía tienes.",
    mentor: "Tu mentor base te ayuda a convertir una inquietud amplia en algo que puedas explorar.",
    connection: "Una persona que vive esa necesidad o alguien que ya empezó un camino parecido.",
    done: "¿Qué escuchaste que cambió tu idea inicial? Anótalo antes de elegir la siguiente acción.",
    stuck: "Reduce el primer paso: identifica a esa persona y prepara una sola pregunta. Revisa con tu mentor qué te impide iniciar la conversación.",
  },
  {
    name: "Aterrizar", element: "Tierra", capacity: "Habilidades",
    question: "¿Cómo lo pruebas en pequeño?",
    situation: "Tienes una idea, pero aún necesitas ponerla frente a alguien que podría necesitarla.",
    route: "Preparas una primera versión sencilla y eliges qué quieres aprender al probarla.",
    challenge: "Tomas una mejora de tu proyecto actual y defines una prueba que puedas realizar.",
    action: "Mostrar una primera versión de mi propuesta a una persona y escuchar su respuesta.",
    ownAction: "Probar una mejora concreta de mi proyecto con una persona usuaria o de mi equipo.",
    evidence: "Qué mostraste, qué respuesta recibiste y qué necesitas ajustar.",
    mentor: "Tu mentor base te ayuda a acotar la prueba. Una sesión con un especialista puede aportar una mirada sobre el tema que necesitas trabajar.",
    connection: "Una posible persona usuaria, cliente o colega con quien probar la propuesta.",
    done: "¿Qué ocurrió al mostrarlo? Separa lo que observaste de lo que suponías y elige un ajuste.",
    stuck: "Revisa el tamaño de la prueba. ¿Puedes mostrar un boceto o explicar la propuesta en una conversación antes de construirla completa?",
  },
  {
    name: "Adaptar", element: "Agua", capacity: "Disciplina y hábitos",
    question: "¿Qué puedes sostener en tu semana?",
    situation: "Ya empezaste. Ahora necesitas hacer espacio para actuar entre el trabajo y tus demás responsabilidades.",
    route: "Organizas acciones que caben en tu semana y revisas lo que ayuda o dificulta realizarlas.",
    challenge: "Observas dónde se está atorando tu avance y ajustas una práctica de tu proyecto.",
    action: "Reservar un espacio concreto de mi semana para realizar una acción del proyecto.",
    ownAction: "Ajustar una actividad que estoy posponiendo y probar una forma más pequeña de hacerla.",
    evidence: "Qué realizaste, qué quedó pendiente y qué cambió al ajustar tu organización.",
    mentor: "Tu mentor base revisa contigo lo que pasó, los obstáculos y el siguiente ajuste. La comunidad aporta otras formas de organizarse.",
    connection: "Alguien con responsabilidades parecidas con quien intercambiar prácticas que sí le funcionan.",
    done: "¿Qué hizo posible que actuaras esta vez? Registra esa condición para intentar sostenerla.",
    stuck: "Mira qué faltó: tiempo, claridad, una habilidad o apoyo. Ajusta una de esas condiciones y acuerda un paso que sí quepa en tu semana.",
  },
  {
    name: "Crecer", element: "Aire", capacity: "Liderazgo",
    question: "¿Con quién puedes dar el siguiente paso?",
    situation: "Ya tienes aprendizajes y avances. Necesitas decidir qué fortalecer y con quién hacerlo.",
    route: "Exploras cómo colaborar, compartir responsabilidades y abrir nuevas posibilidades para tu proyecto.",
    challenge: "Trabajas una decisión de crecimiento, colaboración o reinvención que hoy necesita tu proyecto.",
    action: "Preparar una conversación con alguien con quien podría colaborar.",
    ownAction: "Definir qué apoyo necesito para una mejora y conversar con una posible persona colaboradora.",
    evidence: "Qué puedes aportar, qué apoyo necesitas y qué siguiente paso acordaron.",
    mentor: "Tu mentor base te ayuda a revisar la decisión. Mentores invitados y comunidad aportan perspectivas y oportunidades de conexión.",
    connection: "Una posible persona colaboradora, un aliado o alguien con experiencia en tu siguiente reto.",
    done: "¿Qué siguiente paso quedó acordado? Dale seguimiento; una conexión se construye después de la presentación.",
    stuck: "Antes de buscar más contactos, aclara qué necesitas y qué puedes aportar. Prepara la conversación con tu mentor o con la comunidad.",
  },
] as const;
