import { InstitutionalShell, InstitutionalHero, InstitutionalClosing, contactFor, pageMetadata } from "../../institutional";
const contact = contactFor("Hola, represento una cámara y quiero conocer el Programa de Innovación Empresarial de uHub.");
export const metadata = pageMetadata("Innovación empresarial para cámaras", "Un programa de 12 semanas para que socios de una cámara rediseñen y prueben mejoras en sus negocios con acompañamiento y empresarios mentores.", "/organizaciones/camaras");
export default function CamarasPage() {
  return <InstitutionalShell>
    <InstitutionalHero label="Cámaras y asociaciones empresariales" title="La experiencia de tus socios puede impulsar a otros negocios." intro="Un trimestre para que 30 socios rediseñen y prueben mejoras en su negocio, con la mentoría de empresarios de la cámara. El cierre es una presentación de lo que hicieron y aprendieron." contact={contact} cta="Solicita la propuesta para tu cámara" facts={[["12 semanas", "3 horas de trabajo por semana"], ["30 socios", "Cohorte de referencia"], ["6–8 mentores", "Empresarios con experiencia"]]} status="Primera implementación en preparación. El tamaño del grupo, calendario y alcance se acuerdan con cada cámara." />
    <section className="institutional-section institutional-split"><div><p className="eyebrow">El resultado que buscamos</p><h2>Una mejora probada.<br />Un negocio con siguiente paso.</h2></div><div><p>Cada participante trabaja sobre su negocio actual. Termina con un expediente de innovación que reúne el problema elegido, su propuesta, la evidencia de una prueba y un plan de 90 días.</p><ul className="institutional-checks"><li>Un modelo de negocio revisado y una oportunidad priorizada.</li><li>Un experimento con usuarios o clientes y decisiones basadas en sus resultados.</li><li>Responsables, acciones e indicadores para dar continuidad.</li></ul><p className="institutional-note">El objetivo es generar aprendizaje y capacidad de ejecución. Las ventas y el crecimiento dependen de cada negocio y su contexto.</p></div></section>
    <section className="institutional-section"><p className="eyebrow">El trimestre de trabajo</p><h2>Del negocio de hoy a una nueva posibilidad.</h2><ol className="institutional-sequence"><li><span>Semanas 01–04</span><h3>Revisar y rediseñar</h3><p>Identificar al cliente, revisar el modelo actual y elegir una oportunidad concreta de innovación.</p></li><li><span>Semanas 05–08</span><h3>Organizar y probar</h3><p>Preparar la operación, las herramientas y una prueba con evidencia. La tecnología se elige según el reto.</p></li><li><span>Semanas 09–12</span><h3>Validar y dar continuidad</h3><p>Contrastar resultados con mentores, ajustar y presentar un plan de 90 días en un encuentro de cierre.</p></li></ol><p className="institutional-note">La propuesta incluye revisiones a 30 y 90 días después del cierre para observar continuidad y aprendizajes.</p></section>
    <section className="institutional-band"><p className="eyebrow">Empresarios que acompañan a empresarios</p><h2>Su experiencia se convierte en preguntas útiles.</h2><p>Los mentores trabajan con grupos pequeños sobre un reto, sus datos y una pregunta concreta. Se acuerdan confidencialidad, preparación y límites: la mesa es para acompañar decisiones, sin vender servicios a los participantes.</p></section>
    <section className="institutional-section"><p className="eyebrow">Una colaboración con responsabilidades claras</p><h2>Qué aporta cada parte.</h2><dl className="institutional-roles"><div><dt>La cámara</dt><dd>Convocatoria, sede, coordinación local, vínculo con empresarios mentores y encuentro de cierre.</dd></div><div><dt>uHub × Biné</dt><dd>Diseño del programa, facilitación, herramientas de seguimiento y evaluación de los avances acordados.</dd></div><div><dt>Cada participante</dt><dd>Un reto real, tiempo para probar y evidencia que permita revisar sus decisiones con el grupo.</dd></div></dl><p className="institutional-note">Cuando el reto requiere apoyo técnico especializado, se define su participación y alcance en la propuesta.</p></section>
    <section className="institutional-section institutional-faq"><h2>Antes de decidir.</h2><details><summary>¿Cómo se mide el avance?</summary><p>Con asistencia, expedientes terminados, experimentos realizados, horas de mentoría y continuidad de las acciones. Los indicadores se acuerdan antes de iniciar; no son resultados ya alcanzados.</p></details><details><summary>¿Cuánto cuesta y quién lo opera?</summary><p>Preparamos una cotización según cohorte, sede y acompañamiento. Hoy proponemos una operación guiada por uHub en colaboración con la cámara. La transferencia del modelo a un equipo local sigue en desarrollo.</p></details></section>
    <InstitutionalClosing title="¿Qué reto comparten tus socios?" text="Cuéntanos el perfil de tus afiliados, el grupo que imaginas y tu calendario. A partir de ahí definimos una propuesta." contact={contact} cta="Solicita la propuesta para tu cámara" pdf="/downloads/uhub-camaras.pdf" />
  </InstitutionalShell>;
}
