import { InstitutionalShell, InstitutionalHero, InstitutionalClosing, contactFor, pageMetadata } from "../../institutional";
const contact = contactFor("Hola, represento una A.C. u OSC y quiero conocer el acompañamiento de uHub para innovación y autosostenibilidad.");
export const metadata = pageMetadata("Innovación y autosostenibilidad para OSC", "Acompañamiento para que asociaciones civiles y organizaciones sociales diseñen, prueben y pongan en marcha iniciativas alineadas con su misión.", "/organizaciones/osc");
export default function OscPage() {
  return <InstitutionalShell>
    <InstitutionalHero label="Asociaciones civiles y organizaciones sociales" title="La sostenibilidad también se construye, paso a paso." intro="Acompañamos a tu equipo a diseñar, validar y poner en marcha una iniciativa: mejorar el impacto de su trabajo o desarrollar ingresos propios alineados con su misión." contact={contact} cta="Agenda una conversación" facts={[["2 rutas", "Innovación social o ingresos propios"], ["Un taller inicial", "Diagnóstico y primera propuesta"], ["3–4 meses", "Acompañamiento para iniciativas seleccionadas"]]} status="Formato adaptable a cada organización o cohorte. Primero escuchamos; después proponemos." />
    <p className="institutional-route-note">¿Tu institución apoya a otras personas o proyectos? <a href="/fundaciones">Conoce el seguimiento para fundaciones y convocatorias ↗</a></p>
    <section className="institutional-section institutional-split"><div><p className="eyebrow">El reto cotidiano</p><h2>Cuidar la misión.<br />Encontrar cómo sostenerla.</h2></div><div><p>Atender a la comunidad, conseguir recursos y sostener al equipo deja poco espacio para probar algo nuevo. Una capacitación puede abrir posibilidades; llevarlas a la práctica requiere decisiones, tiempo y seguimiento.</p><p>Partimos de lo que la organización ya sabe hacer, sus recursos y las necesidades que conoce. Elegimos una iniciativa que tenga sentido para su misión y capacidad de ejecución.</p></div></section>
    <section className="institutional-section"><p className="eyebrow">Dos propósitos, un acompañamiento concreto</p><div className="institutional-dual"><article><span>01 / Innovación social</span><h2>Mejorar cómo generas impacto.</h2><p>Revisar un servicio, una experiencia o una forma de trabajo. El resultado buscado es una mejora probada con la población a la que sirve la organización.</p></article><article><span>02 / Autosostenibilidad</span><h2>Probar una fuente de ingresos.</h2><p>Diseñar una oferta, revisar costos y contrastarla con posibles clientes. El resultado buscado es una iniciativa validada y un plan para operarla.</p></article></div><p className="institutional-note">La generación de ingresos es una de las rutas; no es un requisito para todas las iniciativas de innovación social.</p></section>
    <section className="institutional-section"><p className="eyebrow">Cómo lo trabajamos</p><h2>Del diagnóstico a una primera implementación.</h2><ol className="institutional-sequence"><li><span>01 / Preparar</span><h3>Reconocer capacidades</h3><p>Diagnóstico de recursos, experiencia y retos. Taller de un día o dos sesiones para delinear una propuesta.</p></li><li><span>02 / Acompañar</span><h3>Probar una iniciativa</h3><p>En el formato por cohorte, 4–6 organizaciones continúan con mentoría mensual y seguimiento quincenal durante 3–4 meses.</p></li><li><span>03 / Revisar</span><h3>Decidir cómo seguir</h3><p>Bitácora de acciones, evidencia de las pruebas y recomendaciones para dar continuidad dentro de la organización.</p></li></ol><p className="institutional-note">La selección considera pertinencia del proyecto, una persona responsable y tiempo disponible. No se garantizan ventas ni financiamiento.</p></section>
    <section className="institutional-band"><p className="eyebrow">Experiencia previa · Programa con FICOSEC</p><h2>La prueba ocurre en el trabajo real.</h2><p>En el acompañamiento de uHub A.C., Mujeres Resilientes contrastó su oferta de capacitación con empresas; Casa Amiga Esther implementó un proceso de cobro por servicios; Tenda de Cristo puso en marcha Mangiarte.</p><p>Son experiencias documentadas de ese programa. Ayudan a explicar cómo acompañamos; cada colaboración define sus propios objetivos.</p><a className="text-link" href="/organizaciones#casos">Leer los casos y su contexto ↗</a></section>
    <section className="institutional-section institutional-split"><div><p className="eyebrow">Elige la conversación adecuada</p><h2>¿A quién necesitas acompañar?</h2></div><div className="institutional-related"><a href="/fundaciones"><strong>A personas o proyectos que tu fundación apoya</strong><span>Conoce el seguimiento para convocatorias y programas →</span></a><a href="/programa"><strong>A ti, como persona emprendedora</strong><span>Conoce el programa y convocatorias de uHub A.C. →</span></a></div></section>
    <InstitutionalClosing title="¿Qué necesita sostener tu organización?" text="Conversemos sobre la misión, el equipo y la iniciativa que quieres explorar. Podemos trabajar con una organización o diseñar una cohorte." contact={contact} cta="Agenda una conversación" pdf="/downloads/uhub-osc.pdf" />
  </InstitutionalShell>;
}
